server:
  port: 8089
  servlet:
    context-path: /api/v1/user-activity-monitor-service

github:
  activity-detail-url: https://api.github.com/repos/EthicalML/awesome-production-machine-learning/issues

spring:
  data:
    mongodb:
      uri: mongodb+srv://janani20231958:uESIWf8TL2LZeFPL@cluster0.dznm25o.mongodb.net/developer_iq_tracker